### ISSUE TITLE
`skycli deploy` error message is [object Object] 

### ISSUE THREAD

**Issue by david90** [SkygearIO/skycli#29]
Version: 0.1.1-1

Steps to reproduce:
- Init a project called `clitest`
- Edit code of __init__.py
- call command not inside the corresponding project folder

Error Preview:

![screen shot 2017-09-28 at 5 28 20 pm](https://user-images.githubusercontent.com/1916493/30959476-dc7b98e6-a472-11e7-9053-4b769cad0409.png)

**Comment by cheungpat** [comment]
This should be fixed in https://github.com/SkygearIO/skycli/commit/0bcdfb9739708548244833b6bd630fb41d0204d6
